TARGET = power_models
SOURCES = power_models.cc

MODE ?= 
APP_SPECIFIC_CXX_FLAGS ?= -I$(SIM_ROOT)/common/network/components/router -I$(SIM_ROOT)/common/network/components/link

include ../../Makefile.tests
