# Use ia32 for 32-bit, x86_64 for 64-bit
TARGET_ARCH = x86_64

# change only if a different (more up-to-date) version of Boost is installed
BOOST_VERSION = 1_35

# where Pin is uzipped to
PIN_HOME = /afs/csail/group/carbon/tools/pin/current
