SOURCES = spawn.cc
TARGET = spawn
SIM_FLAGS ?= "--general/max_threads_per_core=5 --general/total_cores=6 --thread_scheduling/scheme=round_robin --thread_scheduling/quantum=3"
include ../../Makefile.tests

