SOURCES = spawn.cc
TARGET = spawn
SIM_FLAGS ?= "--general/max_threads_per_core=18 --general/total_cores=20 --thread_scheduling/scheme=round_robin --thread_scheduling/quantum=10"
include ../../Makefile.tests

