
all: $(BUILD_TARGET)

CC = $(MPI_DIR)/bin/mpicc
CXX = $(MPI_DIR)/bin/mpicxx

CXXFLAGS = -I../../user -I../../transport -I../../network -I../../misc -I../../core -I../../../pin/src -c -g -Wall 

LDFLAGS += -lm

CFLAGS = $(CXXFLAGS) -std=c99

CARBON_SOURCES = ../../user/sync_api.c ../../user/capi.c ../../user/thread_support.c
CARBON_OBJECTS = $(CARBON_SOURCES:%.c=%.o)

include ../../makefile.common

# Build rules
$(BUILD_TARGET): $(OBJECTS) $(CARBON_OBJECTS)
	$(CC) -pthread $(LDFLAGS) -o $@ $^

clean:
	-rm -f *.o $(TARGET) sim.out

