
all: $(BUILD_TARGET)

include ../../makefile.gnu.config
FORCE32 ?= 1

CC = $(MPI_DIR)/bin/mpicc
CXX = $(MPI_DIR)/bin/mpicxx

CXXFLAGS = -I../../user -I../../phys_trans -I../../network -I../../misc -I../../core -I../../../pin/src -c -g -Wall 

LDFLAGS += -lm

ifeq (${FORCE32},1)
  CXXFLAGS += -m32
  LDFLAGS += -m32 # -m elf_i386
else
  CXXFLAGS += 
  LDFLAGS += 
endif

CFLAGS = $(CXXFLAGS) -std=c99

CARBON_SOURCES = ../../user/sync_api.c ../../user/capi.c
CARBON_OBJECTS = $(CARBON_SOURCES:%.c=%.o)

## Build rules

%.o : %.c
	$(CC) $(CFLAGS) $(PIN_CXXFLAGS) -o $@ $<

%.o : %.cc
	$(CXX) $(CXXFLAGS) $(PIN_CXXFLAGS) -o $@ $<

$(BUILD_TARGET): $(OBJECTS) $(CARBON_OBJECTS)
	$(CC) -pthread $(LDFLAGS) -o $@ $^

## Cleaning

clean:
	-rm -f *.o $(TARGET) sim.out

