# This makefile is included by all the tests to contain
# default rules.

SIM_ROOT ?= $(CURDIR)/../../../

all: $(BUILD_TARGET)

CC = $(MPI_DIR)/bin/mpicc
CXX = $(MPI_DIR)/bin/mpicxx

CXXFLAGS = -I$(SIM_ROOT)/common -c -g -Wall 

LDFLAGS += -lm

CFLAGS = $(CXXFLAGS) -std=c99

CARBON_SOURCES = ../../user/sync_api.c ../../user/capi.c ../../user/thread_support.c
CARBON_OBJECTS = $(CARBON_SOURCES:%.c=%.o)

# These are the objects required by each test
OBJECTS = $(CPP_SOURCES:%.cc=%.o) $(C_SOURCES:%.c=%.o) 

CLEAN=$(findstring clean,$(MAKECMDGOALS))
ifeq ($(CLEAN),)
include ../../Makefile.common
endif

# Build rules
$(BUILD_TARGET): $(OBJECTS) $(CARBON_OBJECTS)
	$(CC) -pthread $(LDFLAGS) -o $@ $^

ifneq ($(CLEAN),)
clean:
	-rm -f *.o $(TARGET) sim.out
endif

