

PARSEC_DIR=/afs/csail.mit.edu/group/carbon/benchmarks/parsec/parsec-2.1

PARSEC_LIST = blackscholes_parsec

blackscholes_flags ?= 1 in_4.txt prices.txt
bodytrack_flags ?= sequenceB_1 4 1 5 1 0 1

include tests/Makefile.tests

%_parsec:
	mkdir -p $(PARSEC_DIR)/pkgs/apps/$(patsubst %_parsec,%,$@)/run/output_files
	cd $(PARSEC_DIR)/pkgs/apps/$(patsubst %_parsec,%,$@)/run; $(call run_fn,$(MODE),$(PARSEC_DIR)/pkgs/apps/$(patsubst %_parsec,%,$@)/inst/amd64-linux.graphite/bin/$(patsubst %_parsec,%,$@) $($(patsubst %_parsec,%,$@)_flags),$(PROCS),$(SIM_FLAGS),$(CONFIG_FILE))

