PARSEC_HOME=/afs/csail/group/carbon/benchmarks/parsec/parsec-3.0-graphite
PARSEC_LOCAL=$(SIM_ROOT)/tests/parsec/parsec-3.0

APPS = blackscholes bodytrack facesim ferret fluidanimate freqmine raytrace swaptions vips x264
KERNELS = canneal dedup streamcluster

## APPS

blackscholes_flags ?= 64 in_16K.txt prices.txt
# Bodytrack uses a PARSEC thread count of 62 to fit within 64 cores (n+2)
bodytrack_flags ?= sequenceB_2 4 2 2000 5 0 62
facesim_flags ?= -timing -threads 64
ferret_flags ?= corel lsh queries 10 20 15 output.txt
fluidanimate_flags ?=  64 5 in_100K.fluid out.fluid
freqmine_flags ?= kosarak_500k.dat 410
raytrace_flags ?=
swaptions_flags ?= -ns 32 -sm 20000 -nt 32                                                                      
vips_flags ?= im_benchmark barbados_256x288.v output.v
x264_flags ?= --quiet --qp 20 --partitions b8x8,i4x4 --ref 5 --direct auto --b-pyramid --weightb --mixed-refs --no-fast-pskip --me umh --subme 7 --analyse b8x8,i4x4 --threads 32 -o eledream.264 eledream_640x360_32.y4m

# KERNELS

canneal_flags ?= 64 15000 2000 200000.nets 64
dedup_flags ?= -c -p -v -t 20 -i media.dat -o output.dat.ddp
streamcluster_flags ?= 10 20 64 8192 8192 1000 none output.txt 64

include tests/Makefile.tests

APP_FLAGS ?= $($(patsubst %_parsec,%,$@)_flags)
DIRECTORY ?= $(if $(findstring $(patsubst %_parsec,%,$@),$(APPS)),apps,kernels)
COMMAND ?= export GRAPHITE_HOME=$(SIM_ROOT); mkdir -p $(PARSEC_LOCAL)/pkgs/$(DIRECTORY)/$(patsubst %_parsec,%,$@)/run; cd $(PARSEC_LOCAL)/pkgs/$(DIRECTORY)/$(patsubst %_parsec,%,$@)/run; $(call run_fn,$(MODE),$(PARSEC_LOCAL)/pkgs/$(DIRECTORY)/$(patsubst %_parsec,%,$@)/inst/amd64-linux.graphite/bin/$(patsubst %_parsec,%,$@) $(APP_FLAGS),$(SIM_FLAGS))

freqmine_parsec:
	export GRAPHITE_HOME=$(SIM_ROOT);$(PARSEC_LOCAL)/bin/parsecmgmt -a build -p $(patsubst %_parsec,%,$@) -c graphite
	export OMP_NUM_THREADS=64
	$(COMMAND)

vips_parsec:
	export GRAPHITE_HOME=$(SIM_ROOT);$(PARSEC_LOCAL)/bin/parsecmgmt -a build -p $(patsubst %_parsec,%,$@) -c graphite
	export IM_CONCURRENCY=64
	$(COMMAND)

%_parsec:
	export GRAPHITE_HOME=$(SIM_ROOT);$(PARSEC_LOCAL)/bin/parsecmgmt -a build -p $(patsubst %_parsec,%,$@) -c graphite
	$(COMMAND)

setup_parsec:
	cd $(PARSEC_HOME); find -type d  -name .git -prune -o -type d   -printf "mkdir -vp '$(PARSEC_LOCAL)/%p'\n" -o -type f -printf "ln -s '$(PARSEC_HOME)/%p' '$(PARSEC_LOCAL)/%p'\n" | sh
