TMP=$(shell uname -m)
ifeq (${TMP},x86_64)
  PIN_HOME ?= /afs/csail/group/carbon/tools/pin/pin-2.5-24110-gcc.4.0.0-ia32_intel64-linux
else
  PIN_HOME ?= /afs/csail/group/carbon/tools/pin/pin-2.5-24110-gcc.4.0.0-ia32_intel64-linux
endif

PIN_HOME = /afs/csail/group/carbon/tools/pin/current

PIN_BIN=$(PIN_HOME)/ia32/bin/pinbin
PIN_TOOL=$(SIM_ROOT)/lib/pin_sim
PIN_RUN=$(MPI_DIR)/bin/mpirun -np 1 $(PIN_BIN) -mt -t $(PIN_TOOL) 
PIN_RUN_DIST=$(MPI_DIR)/bin/mpirun -np 2 $(PIN_BIN) -mt -t $(PIN_TOOL) 
