BUILD_32 = 1

OBJECTS = $(patsubst %.cpp,%.o,$(patsubst %.c,%.o,$(patsubst %.cc,%.o,$(SOURCES) ) ) )

SIM_ROOT ?= $(CURDIR)/../../..

LD_FLAGS = -L$(SIM_ROOT)/lib 
LD_LIBS = -pthread -lcarbon_sim

CFLAGS = $(CXXFLAGS) -std=c99

all: $(TARGET)

CLEAN=$(findstring clean,$(MAKECMDGOALS))
ifeq ($(CLEAN),)
include $(SIM_ROOT)/common/Makefile.common
endif

CXXFLAGS = -I$(SIM_ROOT)/common/user -I$(SIM_ROOT)/common/misc -c -ggdb3 -Wall -m32

.SUFFIXES:  .o .c .h .cc

$(TARGET): $(OBJECTS) $(SIM_ROOT)/lib/libcarbon_sim.a
	$(CC) $^ -o $@ $(LD_FLAGS) $(LD_LIBS) 

ifneq ($(CLEAN),)
clean:
	-rm -f *.o *.d $(TARGET)
endif
