# This makefile is included by individual tests.
#
# README: Variables that you might care about. Most of these can be
# overridden, which eliminates the variables they are derived from as
# being important. Unfortunately, I don't know how to break make
# functions across multiple lines, so run_fn is completely illegible.
#
# SOURCES - source files to build
# TARGET - name of executable
# RUN - command to run after building; derived from BUILD_MODE, MODE, EXEC, PROCS, and SIM_FLAGS
#
# PROCS - number of processes
# CORES - number of cores
# ENABLE_SM - enable shared memory (true/false)
# APP_FLAGS - flags to pass to the application
# BUILD_MODE - set to build to not run anything
# MODE - set to 'pin' to use pin, set to '' for running application standalone
# CONFIG_FILE - configuration file to use to run the Graphite simulator
# OUTPUT_DIR - directory to write the simulation output
# APP_SPECIFIC_CXX_FLAGS - application-specific CXX flags (e.g., include paths)
# SIM_FLAGS - config flags passed to the simulator. Derived from CORES, PROCS. See sim_flags_fn.
# EXEC - command to run; derived from TARGET and APP_FLAGS

SIM_ROOT ?= $(CURDIR)/../../..

# Run options
include $(SIM_ROOT)/Makefile.config

PIN_BIN=$(PIN_HOME)/intel64/bin/pinbin
PIN_TOOL?=$(SIM_ROOT)/lib/pin_sim

# PIN_RUN=$(PIN_BIN) -pause_tool 10 -tool_exit_timeout 1 -mt -t $(PIN_TOOL)
PIN_RUN=$(PIN_BIN) -tool_exit_timeout 1 -mt -t $(PIN_TOOL)
VALGRIND = # valgrind --leak-check=yes

#CORES ?= 64
#PROCS ?= 1
#ENABLE_SM ?= true 
#APP_FLAGS ?=

APP_SPECIFIC_CXX_FLAGS ?= 
CONFIG_FILE ?= carbon_sim.cfg
OUTPUT_DIR ?= $(shell date +%Y-%m-%d_%H-%M-%S)
CONFIG_FILE_ABS_PATH := $(SIM_ROOT)/$(CONFIG_FILE)
OUTPUT_DIR_ABS_PATH := $(SIM_ROOT)/results/$(OUTPUT_DIR)

BUILD_MODE ?= # Set to build to not run anything
MODE ?= pin # Set to 'pin' to use pin

# Use: $(call sim_flags_fn, $(1-CORES), $(2-PROCS), $(3-ENABLE_SM), $(4-OUTPUT_DIR_ABS_PATH))
sim_flags_fn = -c $(CONFIG_FILE_ABS_PATH)
ifdef CORES
	sim_flags_fn += --general/total_cores=$(1)
endif
ifdef PROCS
	sim_flags_fn += --general/num_processes=$(2)
endif
ifdef ENABLE_SM
	sim_flags_fn += --general/enable_shared_mem=$(3)
endif
ifdef OUTPUT_DIR
	sim_flags_fn += --general/output_dir=$(4)
endif
SIM_FLAGS ?= $(call sim_flags_fn,$(CORES),$(PROCS),$(ENABLE_SM),$(OUTPUT_DIR_ABS_PATH))

EXEC ?= $(CURDIR)/$(TARGET) $(APP_FLAGS) # command thats actually executed
launch_fn = python -u $(SIM_ROOT)/tools/spawn_master.py

# Use: $(call run_fn, $(1-MODE), $(2-EXEC), $(3-SIM_FLAGS))
run_fn = $(if $(findstring build,$(BUILD_MODE)), ,$(if $(findstring pin,$(1)),$(call launch_fn) $(PIN_RUN) $(3) -- $(2),$(call launch_fn) $(VALGRIND) $(2) $(3)))
RUN ?= cd $(SIM_ROOT) ; $(call run_fn,$(MODE),$(EXEC),$(SIM_FLAGS))

# Build targets
all: $(TARGET)
	$(RUN)

# Compiler flags
LD_FLAGS = -static -u CarbonStartSim -u CarbonStopSim -u pthread_create -u pthread_join -L$(SIM_ROOT)/lib
LD_LIBS = -lcarbon_sim -pthread

OBJECTS ?= $(patsubst %.cpp,%.o,$(patsubst %.c,%.o,$(patsubst %.cc,%.o,$(SOURCES) ) ) )

CLEAN=$(findstring clean,$(MAKECMDGOALS))
ifeq ($(CLEAN),)
include $(SIM_ROOT)/common/Makefile.common
endif

CXXFLAGS = $(APP_SPECIFIC_CXX_FLAGS) -I$(SIM_ROOT)/common/user -I$(SIM_ROOT)/common/misc -c -Wall -O2
CFLAGS = $(CXXFLAGS) -std=c99

# Rules
LIB_CARBON=$(SIM_ROOT)/lib/libcarbon_sim.a
LIB_PIN_SIM=$(SIM_ROOT)/lib/pin_sim.so

.PHONY: $(TARGET)

.SUFFIXES:  .o .c .h .cc

# We basically want to try re-making libcarbon_sim.a and pin_sim.so
# and then /if that produces a new library/ recompile the test. There
# is probably some 'correct' way to do this in a makefile that doesn't
# always rebuild the test, but I don't know what it is. (The problem
# is we don't want to include all the dependencies for the libraries
# in this makefile.)
#
# Also, we force recompilation if any of the test object files are
# newer than the target. (Make does this as well but we override it
#  with our if-statement.)
$(TARGET): $(OBJECTS) 
	make -C $(SIM_ROOT)/common
	$(if $(findstring pin,$(MODE)),make -C $(SIM_ROOT)/pin)
	if $(foreach source,$(OBJECTS),[ ! -e $(TARGET) ] || [ $(source) -nt $(TARGET) ] ||) [ $(LIB_CARBON) -nt $(TARGET) ] || [ $(LIB_PIN_SIM) -nt $(TARGET) ]; \
   then $(CXX) $^ -o $@ $(LD_FLAGS) $(LD_LIBS); \
	fi

ifneq ($(MAKECMDGOALS),clean)
include $(OBJECTS:%.o=%.d)
endif

$(LIB_CARBON):
	make -C $(SIM_ROOT)/common

$(LIB_PIN_SIM):
	make -C $(SIM_ROOT)/pin

ifneq ($(CLEAN),)
clean:
	$(RM) *.o *.d $(TARGET)
endif
