CC := gcc
#CFLAGS := -O3 -pthread -D_POSIX_C_SOURCE=200112 
CFLAGS := -g3 -pthread -D_POSIX_C_SOURCE=200112 -m32
CFLAGS := $(CFLAGS) -Wall -W -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wdisabled-optimization
CFLAGS := $(CFLAGS) -Wpadded -Winline -Wpointer-arith -Wsign-compare -Wendif-labels
LDFLAGS := -lm -b64

#BASEDIR := $(HOME)/splash2/codes why did UDel hardcode this? -CPC
#BASEDIR := $(HOME)/src/splash/splash2/codes
#MACROS := $(BASEDIR)/null_macros/c.m4.null.POSIX
MACROS := c.m4.null.POSIX
M4 := m4 -s -Ulen -Uindex

x = *

$(TARGET): $(OBJS)
	$(CC) $(OBJS) $(CFLAGS) -o $(TARGET) $(LDFLAGS)

clean:
	rm -rf *.c *.h *.o $(TARGET)

.SUFFIXES:
.SUFFIXES:	.o .c .C .h .H

.H.h:
	$(M4) $(MACROS) $*.H > $*.h

.C.c:
	$(M4) $(MACROS) $*.C > $*.c

.c.o:
	$(CC) -c $(CFLAGS) $*.c

.C.o:
	$(M4) $(MACROS) $*.C > $*.c
	$(CC) -c $(CFLAGS) $*.c
