CC := gcc
#CFLAGS := -O3 -pthread -D_POSIX_C_SOURCE=200112 
CFLAGS := -g3 -pthread -D_POSIX_C_SOURCE=200112 -m32
CFLAGS := $(CFLAGS) -Wall -W -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wdisabled-optimization
CFLAGS := $(CFLAGS) -Wpadded -Winline -Wpointer-arith -Wsign-compare -Wendif-labels
LDFLAGS := -lm -b64 -lstdc++ -lpthread


CARBON_SOURCES = ../../user/capi.c ../../user/sync_api.c ../../user/thread_support.c
CARBON_OBJECTS = $(CARBON_SOURCES:%.c=%.o) 

BASEDIR := .

# Set to posix to run as normal app
# MACROS := c.m4.null.POSIX

# Set to carbon to run as sim app
# MACROS := c.m4.null.CARBON

M4 := m4 -s -Ulen -Uindex

x = *

$(TARGET): $(OBJS) $(CARBON_OBJECTS)
	$(CC)  $(OBJS) $(CARBON_OBJECTS) $(LDFLAGS) -o $(TARGET) 

clean:
	rm -rf *.c *.h *.o $(TARGET)

.SUFFIXES:
.SUFFIXES:	.o .c .C .h .H

.H.h:
	$(M4) $(MACROS) $*.H > $*.h

.C.c:
	$(M4) $(MACROS) $*.C > $*.c

.c.o:
	$(CC) -c $(CFLAGS) $*.c

.C.o:
	$(M4) $(MACROS) $*.C > $*.c
	$(CC) -c $(CFLAGS) $*.c
