#ifndef __MESSAGE_TYPES_H__
#define __MESSAGE_TYPES_H__

// Different types of messages that get passed to the MCP
typedef enum
{
   MCP_MESSAGE_SYS_CALL,
   MCP_MESSAGE_QUIT,
   MCP_MESSAGE_MUTEX_INIT,
   MCP_MESSAGE_MUTEX_LOCK,
   MCP_MESSAGE_MUTEX_UNLOCK,
   MCP_MESSAGE_COND_INIT,
   MCP_MESSAGE_COND_WAIT,
   MCP_MESSAGE_COND_SIGNAL,
   MCP_MESSAGE_COND_BROADCAST,
   MCP_MESSAGE_BARRIER_INIT,
   MCP_MESSAGE_BARRIER_WAIT,
   MCP_MESSAGE_UTILIZATION_UPDATE,
   MCP_MESSAGE_BROADCAST_COMM_MAP_UPDATE
} MessageTypes;

#endif

