#!/bin/bash
make clean
make
export cores=64
/afs/csail.mit.edu/group/carbon/tools/pin/current/ia32/bin/pinbin -mt -t ../../../pin/bin/pin_sim -mdc -mpf -n ${cores} -- ./cannon -m ${cores} -s ${cores}
#/afs/csail.mit.edu/group/carbon/tools/pin/test/intel64/bin/pinbin -mt -t ../../../pin/bin/pin_sim -mdc -mpf -n 9 -- ./cannon -m 9 -s 9
