TARGET = history_tree
SOURCES = history_tree.cc

CORES ?= 1
ENABLE_SM ?= true
MODE ?=
APP_SPECIFIC_CXX_FLAGS ?= -I$(SIM_ROOT)/common/shared_models -I$(SIM_ROOT)/common/shared_models/queue_models 

include ../../Makefile.tests
