TARGET = history_tree
SOURCES = history_tree.cc

CORES ?= 1
ENABLE_SM ?= true
MODE ?=
APP_SPECIFIC_CXX_FLAGS ?= -I$(SIM_ROOT)/common/performance_model/queue_models -I$(SIM_ROOT)/common/performance_model -I$(SIM_ROOT)/common/misc

include ../../Makefile.tests
