
regress_quick: cannon_unit_test spawn_unit_test simple_dist_unit_test

cannon_unit_test: $(SIM_ROOT)/lib/libcarbon_sim.a
	$(MAKE) -C tests/unit/cannon
	./tests/unit/cannon/cannon -m 4 -s 4

spawn_unit_test: $(SIM_ROOT)/lib/libcarbon_sim.a
	$(MAKE) -C tests/unit/spawn
	./tests/unit/spawn/spawn

simple_dist_unit_test: $(SIM_ROOT)/lib/libcarbon_sim.a
	$(MAKE) -C tests/unit/simple_dist
	mpirun -np 2 ./tests/unit/simple_dist/simple_dist
