#ifndef NETWORK_TYPES_H
#define NETWORK_TYPES_H

enum NetworkType
{
   NETWORK_MAGIC,
   NETWORK_BUS,
   NETWORK_HOP_COUNTER,
   NETWORK_ANALYTICAL_MESH,
   NETWORK_EMESH_HOP_BY_HOP,
   NETWORK_ATAC_OPTICAL_BUS,
   NUM_NETWORK_TYPES
};

#endif // NETWORK_TYPES_H
