#ifndef __PACKET_TYPE_H__
#define __PACKET_TYPE_H__

enum PacketType 
{
   MIN_PACKET_TYPE = 0, 
   INVALID = MIN_PACKET_TYPE, 
   USER,
   SHARED_MEM_REQ,
   SHARED_MEM_EVICT,
   SHARED_MEM_RESPONSE,
   SHARED_MEM_UPDATE_UNEXPECTED,
   SHARED_MEM_ACK,
   MCP_REQUEST_TYPE,
   MCP_RESPONSE_TYPE,
   MAX_PACKET_TYPE = MCP_RESPONSE_TYPE
};

#endif
